#ifndef LIBSHAREDMEMORY_GLOBAL_H
#define LIBSHAREDMEMORY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBSHAREDMEMORY_LIBRARY)
#  define LIBSHAREDMEMORY_EXPORT Q_DECL_EXPORT
#else
#  define LIBSHAREDMEMORY_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBSHAREDMEMORY_GLOBAL_H
